
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';



export const SET_STATUS_MESSAGE = 'SET_STATUS_MESSAGE';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const CLEAR_SEARCH_TEXT = 'CLEAR_SEARCH_TEXT';


export const CRUD_NONE = 'CRUD_NONE';
export const CRUD_INSERTING = 'CRUD_INSERTING';
export const CRUD_INSERT_EDITING = 'CRUD_INSERT_EDITING';
export const CRUD_UPDATE_EDITING = 'CRUD_UPDATE_EDITING';
export const CRUD_SELECTED = 'CRUD_SELECTED';

export const SET_PATHS = 'SET_PATHS';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_VALIDATIONS = 'SET_VALIDATIONS';
export const CLEAR_VALIDATIONS = 'CLEAR_VALIDATIONS';
export const ADD_ERROR = 'ADD_ERROR';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_FORM_DATA = 'SET_FORM_DATA';
export const SET_INITIAL_FORM_DATA = 'SET_INITIAL_FORM_DATA';
export const INSERT_DATA = 'INSERT_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const CANCEL_INSERT = 'CANCEL_INSERT';
export const CANCEL_UPDATE = 'CANCEL_UPDATE';








